
from spacy.lang.en import English
from ahocorasick import Automaton


A=Automaton()
A.add_word("roadster",('BRAND','roadster'))
A.add_word("top",('PRODUCT','top'))
A.add_word("boot",('PRODUCT','boot'))
A.add_word("sandal",('PRODUCT','sandal'))
A.add_word("dress",('PRODUCT','dress'))
A.add_word("glasses",('PRODUCT','glasses'))
A.add_word("saucepan",('PRODUCT','saucepan'))
A.add_word("earphone",('PRODUCT','earphone'))
A.add_word("nylon",('INFO','nylon'))
A.add_word("cotton",('INFO','cotton'))
A.add_word("small",('INFO','small'))
A.add_word("medium",('INFO','medium'))
A.add_word("large",('INFO','large'))
A.add_word("cord",('PRODUCT','cord'))
A.add_word("cover",('PRODUCT','cover'))
A.add_word("case",('PRODUCT','case'))
A.add_word("phone",('PRODUCT','phone'))
A.add_word("lg2000",('BRAND','lg2000'))
A.add_word("shoe",('PRODUCT','shoe'))
A.add_word("warmer",('PRODUCT','warmer'))
A.add_word("shirt",('PRODUCT','shirt'))
A.add_word("xl",('INFO','xl'))
A.add_word("xxl",('INFO','xxl'))
A.add_word("lunch box",('PRODUCT','lunch box'))
A.add_word("battery",('PRODUCT','battery'))
A.add_word("batteries",('PRODUCT','batteries'))
A.add_word("nokia",('BRAND','nokia'))
A.add_word("motorola",('BRAND','motorola'))
A.add_word("verizon",('BRAND','verizon'))
A.add_word("tee",('PRODUCT','tee'))
A.add_word("under armour",('BRAND','under armour'))
A.add_word("bluetooth",('PRODUCT','bluetooth'))
A.add_word("headset",('PRODUCT','headset'))
A.add_word("charger",('PRODUCT','charger'))
A.add_word("ear piece",('PRODUCT','ear piece'))
A.add_word("rope",('PRODUCT','rope'))
A.add_word("jabra",('BRAND','jabra'))
A.add_word("steamer",('PRODUCT','steamer'))
A.add_word("mixer",('PRODUCT','mixer'))
A.add_word("juicer",('PRODUCT','juicer'))
A.add_word("jeans",('PRODUCT','jeans'))
A.add_word("allen solly",('BRAND','allen solly'))
A.add_word("peter england",('BRAND','peter england'))
A.add_word("shorts",('PRODUCT','shorts'))
A.add_word("saree",('PRODUCT','saree'))
A.add_word("skirt",('PRODUCT','skirt'))
A.add_word("curtain",('PRODUCT','curtain'))
A.add_word("cable",('PRODUCT','cable'))
A.add_word("cookware",('PRODUCT','cookware'))
A.add_word("blackberry",('BRAND','blackberry'))
A.add_word("jacket",('PRODUCT','jacket'))
A.add_word("pant",('PRODUCT','pant'))
A.add_word("size",('INFO','size'))
A.add_word("jeans",('PRODUCT','jeans'))
A.add_word("lunchbox",('PRODUCT','lunchbox'))
A.add_word("sony",('BRAND','sony'))
A.add_word("buds",('PRODUCT','buds'))
A.add_word("ear buds",('PRODUCT','ear buds'))
A.add_word("norpro",('BRAND','norpro'))
A.add_word("bealls of florida",('BRAND','bealls of florida'))
A.add_word("heels",('PRODUCT','heels'))
A.add_word("joggers",('PRODUCT','joggers'))
A.add_word("bellies",('PRODUCT','bellies'))
A.add_word("china",('PRODUCT','china'))
A.add_word("cooker",('PRODUCT','cooker'))
A.add_word("slipper",('PRODUCT','slipper'))
A.add_word("earset",('PRODUCT','earset'))
A.add_word("coffee",('PRODUCT','coffee'))
A.add_word("display",('PRODUCT','display'))
A.add_word("ear",('PRODUCT','ear'))
A.add_word("windows",('BRAND','windows'))
A.add_word("samsung",('BRAND','samsung'))
A.add_word("pan",('PRODUCT','pan'))
A.add_word("fabric",('PRODUCT','fabric'))
A.add_word("mug",('PRODUCT','mug'))
A.add_word("wenzel",('BRAND','wenzel'))
A.add_word("fan",('PRODUCT','fan'))
A.add_word("maroon",('INFO','maroon'))
A.add_word("red",('INFO','red'))
A.add_word("black",('INFO','black'))
A.add_word("green",('INFO','green'))
A.add_word("yellow",('INFO','yellow'))
A.add_word("orange",('INFO','orange'))
A.add_word("blue",('INFO','blue'))
A.add_word("cyan",('INFO','cyan'))
A.add_word("turquoise",('INFO','turquoise'))
A.add_word("earpiece",('PRODUCT','earpiece'))
A.add_word("suspenders",('PRODUCT','suspenders'))
A.add_word("underwear",('PRODUCT','underwear'))
A.add_word("clock",('PRODUCT','clock'))
A.add_word("screen protector",('PRODUCT','screen protector'))
A.add_word("boxwave",('BRAND','boxwave'))
A.add_word("sleeveless",('INFO','sleeveless'))
A.add_word("shells",('PRODUCT','shells'))
A.add_word("sheets",('PRODUCT','sheets'))
A.add_word("belt",('PRODUCT','belt'))
A.add_word("earplug",('PRODUCT','earplug'))
A.add_word("cellphone",('PRODUCT','cellphone'))
A.add_word("vacuum",('PRODUCT','vacuum'))
A.add_word("cleaner",('PRODUCT','cleaner'))
A.add_word("dockers",('PRODUCT','dockers'))
A.add_word("corset",('PRODUCT','corset'))
A.add_word("tank-top",('PRODUCT','tank-top'))

